apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
spec:
  rules:
  - host: awesome-applications.apps.sandbox-m3.1530.p1.openshiftapps.com
    http:
      paths:
      - path: /fastapi
        pathType: Prefix
        backend:
          service:
            name: fastapi
            port:
              number: 8080
      - path: /word-picker
        pathType: Prefix
        backend:
          service:
            name: word-picker
            port:
              number: 5000
